### ISSUE TITLE
Support for S3Boto3Storage

### ISSUE THREAD

**Issue by jerinpetergeorge** [jkeifer/drf-chunked-upload#31]
I tried to set the `DRF_CHUNKED_UPLOAD_STORAGE_CLASS` to `S3Boto3Storage` (from [`django-storage`](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html)). 
```python
# drf-chunked-upload Config
# https://github.com/jkeifer/drf-chunked-upload
DRF_CHUNKED_UPLOAD_ABSTRACT_MODEL = False
from storages.backends.s3boto3 import S3Boto3Storage

DRF_CHUNKED_UPLOAD_STORAGE_CLASS = S3Boto3Storage
```
But, I got an error while **"uploading the second chunk"**

```
AttributeError: File was not opened in write mode.
Internal Server Error: /api/v1/polls/files/4fcb004a-4155-4a19-9822-8fe6a8f3f1f7/
Traceback (most recent call last):
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/drf_chunked_upload/views.py", line 59, in put
    return self._put(request, pk=pk, *args, **kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/drf_chunked_upload/views.py", line 221, in _put
    chunked_upload = self._put_chunk(request, pk=pk, *args, **kwargs)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/drf_chunked_upload/views.py", line 194, in _put_chunk
    chunked_upload.append_chunk(chunk, chunk_size=chunk_size)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/drf_chunked_upload/models.py", line 106, in append_chunk
    self.file.write(subchunk)
  File "/home/jpg/.local/share/virtualenvs/generic-django-example-Kc6WXfau/lib/python3.9/site-packages/storages/backends/s3boto3.py", line 168, in write
    raise AttributeError("File was not opened in write mode.")
AttributeError: File was not opened in write mode.

```

**Packages used**

```
django~=3.2.0
drf-chunked-upload~=0.5.1
django-storages[boto3]~=1.13.2
```

**Comment by jkeifer** [comment]
This library should not really care what the backing storage is for a file-like object. Based on some searching around for similar errors, I found this issue: https://github.com/jschneier/django-storages/issues/976. It looks like the `S3Boto3Storage` may be inherently broken with respect to opening in a write mode?

I'm not trying to pass the buck here and say that it's someone else's problem, but it certainly look that way. Any reason to suspect it is actually an issue with drf-chunkd-upload? You can clearly see the method on this side is attempting to open the file in `'ab'` mode: https://github.com/jkeifer/drf-chunked-upload/blob/main/src/drf_chunked_upload/models.py#L102. I would expect the underlying djang-storages/`S3Boto3Storage` abstractions to ensure the handling here is compatible with a normal file, otherwise the abstractions are leaky and therefore somewhat pointless.

**Comment by jkeifer** [comment]
Closing issue due to inactivity.
